### ISSUE TITLE
安装TagEditor后未出现新的搜索框

### ISSUE THREAD

**Issue by Ice-Plume** [EhTagTranslation/UserScripts#14]
已安装EhSyringe扩展，但安装TagEditor后未出现新的搜索框，仍为原始输入框。
浮动窗口功能正常。
chrome版本 108.0.5359.125（正式版本）（64 位）。
Tampermonkey版本 4.18.1。
请问是哪里出了问题，该如何解决？

**Comment by Ice-Plume** [comment]
补充，尝试关闭所有其他插件，只留EhSyringe和TagEditor，问题依旧。

**Comment by Mapaler** [comment]
我现在都没梯子上E站了，没法调试

**Comment by xioxin** [comment]
我发现EhSyringe使用的空格作为分隔符，而添加标签使用的逗号。有空我看看完善下。

**Comment by Mapaler** [comment]
> 我发现EhSyringe使用的空格作为分隔符，而添加标签使用的逗号。有空我看看完善下。

我添加Tag的时候就遇到这个问题，每次都是手动编辑。

**Comment by xioxin** [comment]
已经在这个PR中进行修复. 仍需要一些测试后进行发布.
https://github.com/EhTagTranslation/EhSyringe/pull/1114

可以在这里拿到最新的版本: 
https://github.com/EhTagTranslation/EhSyringe/actions/runs/3883358295
