### ISSUE TITLE
种子的发布时间未按照东八区（或浏览器当地时间）显示

### ISSUE THREAD

**Issue by AgMonk** [EhTagTranslation/UserScripts#16]
![image](https://user-images.githubusercontent.com/31527430/223147927-6f713cb3-4997-42ff-82a5-426874e54990.png)
![image](https://user-images.githubusercontent.com/31527430/223147950-013bf077-b6c0-4af9-a890-714e9fd7670a.png)

**Comment by xioxin** [comment]
真抱歉，我忘了这个issues，现在已经修复了 :joy:

**Comment by AgMonk** [comment]
还漏了一点，图1的“8小时前“上的tooltip里显示的还是GMT时间😂
