### ISSUE TITLE
缩略图工具的切换大图按钮消失了

### ISSUE THREAD

**Issue by blackpumpkin** [EhTagTranslation/UserScripts#18]
RT，这里本来有一个切换“Normal”和“Large”的快捷按钮，现在莫名消失了
![image](https://github.com/EhTagTranslation/UserScripts/assets/51166905/148ec9c2-edeb-4d54-88ba-52b26c28bd03)

**Comment by Mapaler** [comment]
这个是网站改版，这个选项打勾就有了

> Optional UI Elements
> 
> Some historic UI elements are now disabled by default. You can enable those here.
> - [x] Enable thumbnail selector on gallery screen

![firefox_TPwm4dUZg2](https://github.com/EhTagTranslation/UserScripts/assets/6565860/f306a07b-b54d-41f1-8a47-877f792c0cea)
