### ISSUE TITLE
aria2助手只显示查看种子按钮，不能下载图片和下载种子

### ISSUE THREAD

**Issue by zyOverture** [EhTagTranslation/UserScripts#20]
<img width="618" alt="image" src="https://github.com/EhTagTranslation/UserScripts/assets/39595404/d8404ff6-5355-4da6-816c-9e04b708af63">
<img width="1371" alt="image" src="https://github.com/EhTagTranslation/UserScripts/assets/39595404/be8add1c-9f8e-4de1-a3a6-9ccf1a0dddf1">

如图 只有首页有一个查看种子的按钮 其他按钮都没有显示

**Comment by zyOverture** [comment]
<img width="1775" alt="image" src="https://github.com/EhTagTranslation/UserScripts/assets/39595404/7fda4adb-6454-4c86-921f-e13dba210de1">

附上控制台报错信息

**Comment by xioxin** [comment]
已修复
