### ISSUE TITLE
eh磁力链助手0.2更新后无效

### ISSUE THREAD

**Issue by bearpool** [EhTagTranslation/UserScripts#22]
chrome 124.0.6367.62
Tampermonkey 5.1.1

前两天的更新后种子获取页面就看不到“复制磁力链”的按钮，切换为0.1版本后可正常使用

**Comment by xioxin** [comment]
0.2 修复了 #21 
目前我这里0.2版本，表站、里站测试是正常的。而0.1 是失效的。难道e站在进行AB测试？

可以打开种子下载页面右键“查看网页源代码”，将代码发给我吗？如果你担心泄露隐私，你可以使用隐身窗口在未登录状态下复制。

**Comment by OpportunityLiu** [comment]
八成是插件冲突。。

**Comment by lumster** [comment]
同样的问题。其他插件全部禁用问题也没有解决。

**Comment by zxc173123** [comment]
> 0.2 修复了 #21 目前我这里0.2版本，表站、里站测试是正常的。而0.1 是失效的。难道e站在进行AB测试？
> 
> 可以打开种子下载页面右键“查看网页源代码”，将代码发给我吗？如果你担心泄露隐私，你可以使用隐身窗口在未登录状态下复制。

我也是无效，已关闭其他脚本也是这样

**Comment by zxc173123** [comment]
> 同样的问题。其他插件全部禁用问题也没有解决。

找到原因了，要自己加用户匹配https://exhentai.org/g/*/*

**Comment by xioxin** [comment]
> > 同样的问题。其他插件全部禁用问题也没有解决。
> 
> 找到原因了，要自己加用户匹配https://exhentai.org/g/*/*

谢谢你的提醒。

我检查匹配注意到一个警告 `Using @include is potentially unsafe and may be obsolete in Manifest v3 in early 2023. Please switch to @match.` 

我已经在 0.3 版本将 `include` 替换到了 `match`  或许可以解决这个问题。不过如果真是这个问题，即便切换会0.1也不应该会恢复的。只能先这样试试了。

**Comment by bynejake** [comment]
![image](https://github.com/user-attachments/assets/25f7b845-16c5-4d91-87e3-d767d4bf966d)

我这边使用还是有问题，上图是我自己改过的

**Comment by xioxin** [comment]
@bynejake 感谢你的反馈，我意识到了问题所在，确实是插件冲突。
是另一个插件"EhAria2下载助手" 会将按钮从input改为button。😂
马上修复这一问题

**Comment by xioxin** [comment]
已修复

**Comment by OpportunityLiu** [comment]
> @bynejake 感谢你的反馈，我意识到了问题所在，确实是插件冲突。
> 是另一个插件 ~"EhAria2下载助手"~ "EhSyringe" 会将按钮从input改为button。😂
> 马上修复这一问题

有些 input 的 value 在提交的时候会用到，没法翻译，最后就改成这样了
