### ISSUE TITLE
[Bug] 画廊详情页标签着色导致边界的虚实线看不到

### ISSUE THREAD

**Issue by Hayakee** [EhTagTranslation/UserScripts#24]
我是标签壬，每天在画廊进行标签的投票和发起，因为画廊详情页没有和画廊列表一样给标签着色看着很不爽，标签着色脚本解决了这个问题。
但随之而来的就是标签边界的虚实线看不到，导致我无法确定这个标签是否还可以继续投票。
另外由于投票会改变标签的颜色（赞成是绿色，反对是红色），所以还需要展示着色后标签投票情况的标志。
未启用脚本：
![image](https://github.com/user-attachments/assets/ca73f34e-14f4-4935-be1b-836ee41c9a26)
启用脚本：（对于着色的标签投票情况无法得知）
![image](https://github.com/user-attachments/assets/d69ce2a0-132c-4bca-a1da-86216b6adc40)
已找到其他项目的解决方式供开发者参考：https://github.com/hymbz/ComicReadScript?tab=readme-ov-file#%E6%A0%87%E7%AD%BE%E6%9F%93%E8%89%B2
效果如下：
![image](https://github.com/user-attachments/assets/2dc513fe-3701-4fc8-8f26-ebbaba81990e)

**Comment by xioxin** [comment]
已修复
![img](https://github.com/user-attachments/assets/1301b4f4-66f2-4fc0-b229-7a4d0160f174)
