### ISSUE TITLE
画廊详情页大于200后无法正常使用插件

### ISSUE THREAD

**Issue by jhc2414169248** [EhTagTranslation/UserScripts#4]
我的hathpark开了页面扩大，现在100以后的都无法正常使用插件，请问如何更改可以正常使用？

**Comment by Mapaler** [comment]
所以你说的到底是哪个插件？

**Comment by jhc2414169248** [comment]
> 所以你说的到底是哪个插件？

你好，我说的是EhAria2下载助手这个插件。我以为直接提交issue就可以定位到这个项目下面，实在是非常抱歉。

**Comment by Mapaler** [comment]
这里是一堆小功能脚本的集合，有不同的开发者。

**Comment by jhc2414169248** [comment]
> 这里是一堆小功能脚本的集合，有不同的开发者。

那么请问，在这里反馈问题，可以被下载助手的作者收到吗

**Comment by Mapaler** [comment]
上面已经分配了，但他是专业人士，不是经常来。

**Comment by xioxin** [comment]
抱歉，刚看到消息。目前我尚未解锁 Paging Enlargement II ，
可以提供下更详细的描述吗，最好配合截图。
是只要选择200就全部不好用了 还是后半部分不好用。

**Comment by jhc2414169248** [comment]
> 抱歉，刚看到消息。目前我尚未解锁 Paging Enlargement II ， 可以提供下更详细的描述吗，最好配合截图。 是选择200之后全部不好用了 还是后半部分不好用。

你好，是选择200过后的后半部分无法正常使用，前半部分正常

**Comment by xioxin** [comment]
右键 “检查” 在 “控制台”（Console）选项卡下有没有报错，有的话截个图

**Comment by xioxin** [comment]
已经解锁 Paging Enlargement II，未发现问题。暂时关闭这个issues

**Comment by Mapaler** [comment]
> 已经解锁 Paging Enlargement II，未发现问题。暂时关闭这个issues

![1675415888361_firefox](https://user-images.githubusercontent.com/6565860/216560998-8fad1987-bb69-4092-9042-1900ff288cc1.png)
我都开了好多年了

**Comment by xioxin** [comment]
当时应该问你要点 😹
