### ISSUE TITLE
点击一键下载提示：一键下载失败:Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by dhr88331** [EhTagTranslation/UserScripts#5]
win10 edge浏览器，点击列表左侧的提示：一键下载失败:Cannot read properties of null (reading '1')
请问是我哪边设置错了吗

**Comment by xioxin** [comment]
一键下载是使用 存档下载（Archive Download），你需要登录账号并且点数充足（GP 或 Credits）。

**Comment by a419416951** [comment]
一键下载不成功，只能打开存档再发送到Aria2才能下，请问是漏了什么设置吗

**Comment by a419416951** [comment]
明白了，我在EH上设置了自动下载

**Comment by a419416951** [comment]
大佬这个是什么原因呢

**Comment by xioxin** [comment]
@a419416951 安全链接建立失败, 看起来是网络问题.
