### ISSUE TITLE
使用“EhAria2下载助手”下载的文件，文件体积异常，且总是被命名为纯数字

### ISSUE THREAD

**Issue by Nigel-NI** [EhTagTranslation/UserScripts#6]
使用插件在收藏界面使用一键下载功能时，下载的文件只有2kb，且文件名称默认为2，且没有后缀。下载完成后脚本提示“_完成 类型：_”，如下图所示。进入“Archive Download”界面，通过按钮“发送到aria2”下载时文件体积正常，但文件名仍然是纯数字。
![image](https://user-images.githubusercontent.com/23294384/184500316-3b5079f4-7dee-4998-a022-ea8a282dc3bd.png)
![image](https://user-images.githubusercontent.com/23294384/184500418-444b1b62-0de6-440b-a0b7-84e5ca22de7b.png)

**aria2界面显示的信息如下**（部分敏感信息已做处理）：
![image](https://user-images.githubusercontent.com/23294384/184500473-8080a7d3-a47f-4332-8fb0-5111d474a231.png)

依据sleazyfork的反馈，文件名的问题貌似是因aria2配置的问题所导致，但鄙人能力有限，花了一个多小时寻找如何修改aria2配置文件以实现从服务端自动获取文件名的有关配置，却一无所获。还请大佬指点一二，非常感谢！

PS: 这是我正在使用的aria2.conf配置文件内容，供参考：
<details><summary>aria2.conf</summary>

<p>

```ruby
## '#'开头为注释内容, 选项都有相应的注释说明, 根据需要修改 ##
## 被注释的选项填写的是默认值, 建议在需要修改时再取消注释  ##

## 文件保存相关 ##

# 文件的保存路径(可使用绝对路径或相对路径), 默认: 当前启动位置
dir=E:\Downloads\aria2
# 启用磁盘缓存, 0为禁用缓存, 需1.16以上版本, 默认:16M
disk-cache=32M
# 文件预分配方式, 能有效降低磁盘碎片, 默认:prealloc
# 预分配所需时间: none < falloc ? trunc < prealloc
# falloc和trunc则需要文件系统和内核支持
# NTFS建议使用falloc, EXT3/4建议trunc, MAC 下需要注释此项
file-allocation=none
# 断点续传
continue=true

## 下载连接相关 ##

# 最大同时下载任务数, 运行时可修改, 默认:5
max-concurrent-downloads=2
# 同一服务器连接数, 添加时可指定, 默认:1
max-connection-per-server=8
# 最小文件分片大小, 添加时可指定, 取值范围1M -1024M, 默认:20M
# 假定size=10M, 文件为20MiB 则使用两个来源下载; 文件为15MiB 则使用一个来源下载
min-split-size=10M
# 单个任务最大线程数, 添加时可指定, 默认:5
split=8
# 整体下载速度限制, 运行时可修改, 默认:0
#max-overall-download-limit=0
# 单个任务下载速度限制, 默认:0
#max-download-limit=0
# 整体上传速度限制, 运行时可修改, 默认:0
#max-overall-upload-limit=0
# 单个任务上传速度限制, 默认:0
#max-upload-limit=0
# 禁用IPv6, 默认:false
disable-ipv6=true

## 进度保存相关 ##

# 从会话文件中读取下载任务
input-file=aria2.session
# 在Aria2退出时保存`错误/未完成`的下载任务到会话文件
save-session=aria2.session
# 定时保存会话, 0为退出时才保存, 需1.16.1以上版本, 默认:0
save-session-interval=60

## RPC相关设置 ##

# 启用RPC, 默认:false
enable-rpc=true
# 允许所有来源, 默认:false
rpc-allow-origin-all=true
# 允许非外部访问, 默认:false
rpc-listen-all=true
# 事件轮询方式, 取值:[epoll, kqueue, port, poll, select], 不同系统默认值不同
#event-poll=select
# RPC监听端口, 端口被占用时可以修改, 默认:6800
rpc-listen-port=6800
#用户密钥
rpc-secret=0000

## BT/PT下载相关 ##

#（略）

```

</p>

</details>

**Comment by xioxin** [comment]
能用记事本打开那个2k的文件看看内容吗？

**Comment by Mapaler** [comment]
这是只下载了显示下载连接的的网页啊

**Comment by lilyblessing** [comment]
我是sleazyfork该问题反馈者，抱歉提醒邮件被收进垃圾箱了没在第一时间看到，在此处回复一下仅供参考。当时的问题同样是文件名为纯数字无后缀，但不同的是文件体积正常，可被解压；即下载文件仅是无法获取到文件名信息的正常压缩包。排查后发现应当开启aria2配置中的 “获取服务器文件时间” ，开启后一切正常。
