### ISSUE TITLE
除了文件名不是纯数字了外，其他各种问题怎么没人解答下载。

### ISSUE THREAD

**Issue by 512382994** [EhTagTranslation/UserScripts#9]
⠚ 错误 (1: Download aborted.) 进度：0.00% 类型：

⠋ 错误 (22: HTTP 返回头无效或无法识别.) 进度：- 类型：
⠙ 📥 下载中 进度：43.51% 速度：3.48 KB/s 类型：zip
啥情况都有，有的能下载有的不能下载，下载速度也慢得下不动，又有一些能正常下载的。百花齐放了都。

**Comment by xioxin** [comment]
可能与网络有关，这些错误信息都是Aria2发生的错误。请自行检查Aria2的相关日志排查问题，或尝试为Aria2添加代理。
